#first run:# xhost
app:
  tty: true
  build: ./
  net: "host"
  ports:
      - "8888:8888"
  environment:
     - DISPLAY=unix$DISPLAY
     - XAUTHORITY=$XAUTHORITY
  devices:
     - /dev/video0   #web camera
#     - /dev/ttyUSB0 #arduino

  volumes:
     - /home/dima/gitHub/faceDetect:/root/app
     - /tmp
     - /tmp/.X11-unix:/tmp/.X11-unix:ro
